plugins { id 'com.android.application' }

android {
    namespace 'com.kartar.classes'
    compileSdk 35
    defaultConfig {
        applicationId 'com.kartar.classes'
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
    signingConfigs {
        release {
            storeFile file("${project.projectDir}/kartar-release.jks")
            storePassword "KartarClasses2026!"
            keyAlias "kartar"
            keyPassword "KartarClasses2026!"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}